export const SET_ONE_QUESTION = 'SET_ONE_QUESTION';
export const SET_MANY_QUESTIONS = 'SET_MANY_QUESTIONS';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const UPDATE_QUESTION = 'UPDATE_QUESTION';
