export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const CLEAR_USER_PROFILE = 'CLEAR_USER_PROFILE';
export const REMOVE_FROM_WORKSPACES_ARRAY = 'REMOVE_FROM_WORKSPACES_ARRAY';
