export const SET_USER = 'SET_USER';
export const SET_KEEP_LOGGED_IN = 'SET_KEEP_LOGGED_IN';
export const CLEAR_USER = 'CLEAR_USER';
export const SET_AUTH_ERROR_MESSAGE = 'SET_AUTH_ERROR_MESSAGE';
export const CLEAR_AUTH_ERROR_MESSAGE = 'CLEAR_AUTH_ERROR_MESSAGE';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const CLEAR_AUTH_LOADING = 'CLEAR_AUTH_LOADING';
