export const SET_WORKSPACES = 'CACHE_WORKSPACES';
export const CLEAR_WORKSPACES = 'CLEAR_WORKSPACES';
export const DELETE_WORKSPACE = 'DELETE_WORKSPACE';
export const UPDATE_WORKSPACE_ENTITY_DETAILS = 'UPDATE_WORKSPACE_ENTITY_DETAILS';

export const SET_WORKSPACE_COMPONENT = 'SET_WORKSPACE_COMPONENT';
export const DELETE_WORKSPACE_COMPONENT = 'DELETE_COMPONENT';
export const CLEAR_WORKSPACE_COMPONENTS = 'CLEAR_COMPONENTS';
export const UPDATE_WORKSPACE_COMPONENTS = 'UPDATE_WORKSPACE_COMPONENTS';

export const CLEAR_WORKSPACE_IS_LOADING = 'CLEAR_WORKSPACE_IS_LOADING';
export const SET_WORKSPACE_IS_LOADING = 'SET_WORKSPACE_IS_LOADING';

export const SET_NEW_WORKSPACE_ERROR_MSG = 'SET_NEW_WORKSPACE_ERROR_MSG';
export const CLEAR_NEW_WORKSPACE_ERROR_MSG = 'CLEAR_NEW_WORKSPACE_ERROR_MSG';
export const SET_ONE_WORKSPACE = 'SET_ONE_WORKSPACE';
export const UPDATE_WORKSPACE_COMPONENT = 'UPDATE_WORKSPACE_COMPONENT';
